config/routes.rb
MadeInAtx2::Application.routes.draw do
  
  root to: 'companies#index', as: 'home'

  resources :companies

end

app/models/company.rb
require 'open-uri'
require 'json'

class Company < ActiveRecord::Base
  attr_accessible :name, :category_code, :homepage_url, :overview, :image
  # validates_presence_of :name

		#-------Crunchbase::API.key = "bxqwjskgyrg2hjykcrc6dbpy"
	json_file = JSON.parse(open("http://api.crunchbase.com/v/1/search.js?geo=78701&range=15&page=1&api_key=bxqwjskgyrg2hjykcrc6dbpy").read)
	crunchbase_companies = json_file["results"] 
	    #-------Store API data into the DB:
	unless @company.present? 
		crunchbase_companies.each do |crunchbase_company|
  		@company = Company.create(:name => crunchbase_company["name"], :category_code => crunchbase_company["category_code"], :homepage_url => crunchbase_company["homepage_url"], :overview => crunchbase_company["overview"], :image => crunchbase_company["image"])
    end
  end
end

	
# Crunchbase API data format (the 'results' key is an array containing a hash for each company:
# Example:
# "name" => "Skylist"  (***)
# "category_code" => "web" (***)
# "description" => "Doing great things for the web!"
# "permalink" => "skylink"
# "crunchbase_url" => "http://www.crunchbase.com/company/skylist"
# "homepage_url"=>"http://www.skylist.com" (***)
# "namespace"=>"company"
# "overview"=>"Founded in 1996, SKYLIST is an email service provider. " (***)
# "image"=> {"available_sizes"=>[[[148, 35], "assets/images/resized/0002/3317/23317v1-max-150x150.png"], [[148, 35], "assets/images/resized/0002/3317/23317v1-max-250x250.png"], [[148, 35], "assets/images/resized/0002/3317/23317v1-max-450x450.png"]], "attribution"=>nil} (***)
#  "offices"=>[{"description"=>nil, "address1"=>"", "address2"=>"", "zip_code"=>"78701", "city"=>"Austin", "state_code"=>"TX", "country_code"=>"USA", "latitude"=>30.2672, "longitude"=>-97.742306}]} (***)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # Try Groupon API, Seek Geek API (Taylor/Josh did one), Good Reads API (MKS Challenge) - look at MKS students code for Biblio
  
  def index
  	@companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new 
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
    	redirect_to company_path(@company.id), notice: "Company added successfully"
 	  else
 	  	render action: 'new'
 	  end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    
    if @company.update_attributes(params[:company])
      redirect_to company_path(@company.id), notice: "Company was updated succesfully"
    else
      render 'edit_company' 
    end 
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    
    redirect_to companies_path 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title(company)
		if company
			"#{company.name} | Austin Tech Companies"
		else
			"Austin Tech Companies"
		end
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.haml
%h1 Edit a Company
%br

= form_for(@company) do |form|
	- if @company.errors.any?
		%h2= pluralize(@company.errors.count, "error") + "prohibited this link from being saved:"
		%ul
			- @company.errors.full_messages.each do |msg|
				%li= msg

	.field
		= form.label :name
		%br
	.field
		= form.text_field :name
		%br
		%br

	.field
		= form.label :address1, "Address"
		%br
	.field
		= form.text_field :address1
		%br
		%br

	.field
		= form.label :website
		%br
	.field
		= form.text_field :website
		%br
		%br

	.field
		= form.label :description
		%br
	.field
		= form.text_area :description, :cols => "60", :rows => "10"
		%br
		%br
	.actions
		= form.submit "Update"
	%br
	.actions
		= link_to 'Back', companies_path

app/views/companies/index.html.haml
/ ------This view is for the Homepage index (companies#index)--------

/ ----------- TEXT to add a company --------
/ = link_to "New Company", new_company_path

/ ----------- BUTTON to add a company --------
.button
	%a{:href => 'companies/new', :class => 'button'}
		%img{:src=> 'assets/Button.13.Peter-c.jpg'}

/  ---------  LISTING Companies from CrunchBase API ---------
- @companies.each do |company|
	.company
		.title
			%h3
				=link_to company.name, 'company_path(company)'

		.block
			.logo
				= image_tag "http://www.crunchbase.com/company/#{company['name']}/#{company['image']}"
			.info
				.overview
					= company["overview"]
				.info2
					%p= link_to 'Website', company["homepage_url"], {:target => "_blank"}
					%p= "Category: #{company['category_code']}"
				%p
					= link_to 'Edit', 'edit_company_path(company)'
					= link_to 'Delete', company, :confirm => 'Are you sure?', :method => :delete

/ ------- Inspecting Objects from CrunchBase API ------
/ %b
/ 	crunchbase_companies.class: 
/ %p
/ 	= @crunchbase_companies.class
/ %b
/ 	crunchbase_companies[0].class:
/ %p
/ 	= @crunchbase_companies[0].class

/ %b
/ 	json_file.inspect:
/ %p
/ 	= @json_file.inspect

/ linh_to helper in html syntax: 
/ <a href="/company/4" data-confirm="Are you sure?" data-method="delete">Delete</a> 
/ Jquery ujs pauses the href from redirecting and runs the data stuff first.
/ The "delete" method generates a temp, blank form and submits it instead of the get request.

app/views/companies/new.html.haml
%h1 Add a Company
%br

= form_for(@company) do |l|
	- if @company.errors.any?
		%h2= pluralize(@company.errors.count, "error") + " prohibited this link from being saved:"
		%br
		%ul.error
			- @company.errors.full_messages.each do |msg|
				%li= msg
	%br

	.field
		= l.label :name
	.field
		= l.text_field :name
		%br
		%br
		
	.field
		= l.label :address1, "Address"
	.field
		= l.text_field :address1
		%br
		%br
		
	.field
		= l.label :website
	.field
		= l.text_field :website
		%br
		%br

	.field
		= l.label :description, "Description: add 1-3 sentence description"
	.field
		= l.text_area :description, :cols => "60", :rows => "10"
		%br

	.actions= l.submit "Submit"

app/views/companies/show.html.haml
/ ------This view is for a specific Company (companies#show) --------

/ Try using these to take a screen snapshot:

/ http://rubygems.org/gems/snapurl

/ Use Firefox "headless" to take screenshots of web pages.

/ http://mythumbshot.com/

/ I use IMGKit gem for that: https://github.com/csquared/IMGKit
/ Related topic: How to respond_to PNG or JPG in Rails and generate image from HTML?
/ http://stackoverflow.com/questions/5135666/how-to-respond-to-png-or-jpg-in-rails-and-generate-image-from-html


.notice
	= flash[:notice]
%h1 
	=@company.name

.actions
	= link_to 'Back to List', companies_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link href='http://fonts.googleapis.com/css?family=Nosifer|Cabin+Condensed|Londrina+Sketch|Frijole|Source+Code+Pro' rel='stylesheet' type='text/css'>

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<title><%= page_title(@company) %></title>
	</head>

	<body>
		<header>
			<a href="/">
				<h1>Made.In.Atx</h1>
			</a>
			<nav>
				<span class="tagline"> A caboodle of technology companies in Austin, TX</span>
			</nav>
		</header>	
<!-- 		<div> 
			<img src="assets/button-add-company.jpg" title ="Add a Company">
		</div> -->
		<%= yield %>
	</body>

</html>